/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 girl-sitting-swinging-legs.glb --transform 
Files: girl-sitting-swinging-legs.glb [282.03KB] > girl-sitting-swinging-legs-transformed.glb [613.78KB] (-118%)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model_Girl(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/girl-sitting-swinging-legs-transformed.glb');
  const { actions } = useAnimations(animations, group);

//  console.log(actions); // use to find the armature name to add to the Effect actions in next section

  useEffect(() => {
    actions['Armature|mixamo.com|Layer0'].play(); 
    });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Beta_Joints" geometry={nodes.Beta_Joints.geometry} material={materials.Beta_Joints_MAT1} skeleton={nodes.Beta_Joints.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
        <skinnedMesh name="Beta_Surface" geometry={nodes.Beta_Surface.geometry} material={materials.Beta_HighLimbsGeoSG3} skeleton={nodes.Beta_Surface.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/girl-sitting-swinging-legs-transformed.glb')